{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5554d630-8873-43d3-a4a6-fe4eb06f092f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#1\n",
    "#When creating a custom exception in Python, it is recommended to inherit from the built-in `Exception` class or one of its subclasses. \n",
    "#Here are a few reasons why it is beneficial to use the `Exception` class as the base class for custom exceptions:\n",
    "\n",
    "#1. Consistency: Inheriting from `Exception` ensures that your custom exception follows the same design and behavior as other built-in exceptions \n",
    "#in Python. This consistency makes it easier for developers to understand and work with your custom exception, as they are already familiar with \n",
    "#the methods and attributes provided by the `Exception` class.\n",
    "\n",
    "#2. Error handling: By inheriting from `Exception`, your custom exception can be caught using a broader `except` statement that handles general \n",
    "#exceptions. For example, if you only inherit from a custom class, catching your exception may require an additional `except` clause. Inheriting \n",
    "#from `Exception` allows your custom exception to be caught using a single `except` statement that handles any exception derived from the \n",
    "#`Exception` class.\n",
    "\n",
    "#3. Compatibility: Inheriting from `Exception` ensures that your custom exception is compatible with existing exception handling mechanisms \n",
    "#and practices in Python. It allows you to leverage the standard exception handling features like `try-except` blocks, traceback information,\n",
    "#and exception chaining.\n",
    "\n",
    "#4. Future-proofing: The `Exception` class is part of the Python language's core exception hierarchy, and it is unlikely to undergo major changes.\n",
    "#By inheriting from `Exception`, you ensure that your custom exception will remain compatible with future versions of Python.\n",
    "\n",
    "#5. Additional functionality: The `Exception` class provides various methods and attributes that can be helpful for exception handling, \n",
    "#such as `__str__` to define a custom error message, `args` to access exception arguments, and `with_traceback` to set a custom traceback.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "75a638f9-1f3f-4343-a3f0-36506867023a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "    TypeError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "    OSError\n",
      "    EOFError\n",
      "    RuntimeError\n",
      "    NameError\n",
      "    AttributeError\n",
      "    SyntaxError\n",
      "    LookupError\n",
      "    ValueError\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "    SystemError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "    PickleError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "    ConfigurableError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "    Error\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "    Error\n",
      "    HTTPException\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "    ParseBaseException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n",
      "\n",
      "GeneratorExit\n",
      "\n",
      "SystemExit\n",
      "\n",
      "KeyboardInterrupt\n",
      "\n",
      "CancelledError\n",
      "\n",
      "AbortThread\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#2\n",
    "def print_exception_hierarchy():\n",
    "    for exception_class in BaseException.__subclasses__():\n",
    "        print(exception_class.__name__)\n",
    "        for subclass in exception_class.__subclasses__():\n",
    "            print(f\"    {subclass.__name__}\")\n",
    "        print()\n",
    "\n",
    "print_exception_hierarchy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "c276cca4-97ca-4907-96ee-f9e15a0dd3de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: Division by zero is not allowed.\n",
      "Result: 85070591730234615847396907784232501249\n"
     ]
    }
   ],
   "source": [
    "#3\n",
    "#The `ArithmeticError` class is a base class for all errors related to arithmetic operations in Python. It is a subclass of the built-in\n",
    "#`Exception` class. Some common errors defined in the `ArithmeticError` class include:\n",
    "\n",
    "#1.ZeroDivisionError: This error occurs when a division or modulo operation is performed with zero as the divisor. \n",
    "#It indicates that the division or modulo operation is mathematically undefined.\n",
    "#Example:\n",
    "dividend = 10\n",
    "divisor = 0\n",
    "try:\n",
    "    result = dividend / divisor\n",
    "    print(\"Result:\", result)\n",
    "except ZeroDivisionError:\n",
    "    print(\"Error: Division by zero is not allowed.\")\n",
    "        \n",
    "#In this example, dividing `10` by `0` would raise a `ZeroDivisionError`. The code catches the exception using a `try-except` block \n",
    "# and handles it by printing an error message.\n",
    "\n",
    "#2.OverflowError: This error occurs when the result of an arithmetic operation exceeds the maximum representable value for the data type being used.\n",
    "#It typically occurs in situations where the calculated value is too large to fit within the memory allocated for that data type.\n",
    "#Example:\n",
    "import sys\n",
    "\n",
    "large_number = sys.maxsize\n",
    "try:\n",
    "    result = large_number * large_number\n",
    "    print(\"Result:\", result)\n",
    "except OverflowError:\n",
    "    print(\"Error: The result exceeds the maximum representable value.\")\n",
    "\n",
    "#In this example, multiplying a large number (`sys.maxsize`) by itself would result in a value that exceeds the maximum representable value\n",
    "#for the data type. This would raise an `OverflowError`, which is caught and handled by printing an error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4e4f9617-854b-4e21-a0de-34f35565d144",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Key not found in the dictionary.\n",
      "Index is out of range.\n"
     ]
    }
   ],
   "source": [
    "#4\n",
    "#The `LookupError` class is used as a base class for exceptions that occur when performing a lookup operation on a collection \n",
    "#(such as a list, dictionary, or tuple) or when accessing elements by their indices. It serves as a common superclass for more \n",
    "#specific lookup-related exceptions.\n",
    "\n",
    "#Let's discuss two specific subclasses of `LookupError`: `KeyError` and `IndexError`.\n",
    "\n",
    "#1.KeyError: This exception is raised when a dictionary key is not found. It occurs when you try to access a non-existent key in a dictionary.\n",
    "\n",
    "#Here's an example:\n",
    "my_dict = {\"apple\": 1, \"banana\": 2, \"orange\": 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict[\"grape\"]\n",
    "    print(value)\n",
    "except KeyError:\n",
    "    print(\"Key not found in the dictionary.\")\n",
    "\n",
    "\n",
    "#In this example, we attempt to access the value associated with the key \"grape\" in the `my_dict` dictionary. However, since \"grape\" is not a key\n",
    "#in the dictionary, a `KeyError` is raised. We catch the exception using a `try-except` block and print a custom error message.\n",
    "\n",
    "#2.IndexError: This exception is raised when a sequence index is out of range. It occurs when you try to access an element from a list,\n",
    "#tuple, or other sequence using an invalid index.\n",
    "\n",
    "#Here's an example:\n",
    "my_list = [1, 2, 3, 4, 5]\n",
    "\n",
    "try:\n",
    "    value = my_list[10]\n",
    "    print(value)\n",
    "except IndexError:\n",
    "    print(\"Index is out of range.\")\n",
    "#In this example, we try to access the element at index 10 in the `my_list` list. However, since `my_list` has only five elements, \n",
    "#the index 10 is out of range, causing an `IndexError` to be raised. We catch the exception using a `try-except` block and \n",
    "#print a custom error message.\n",
    "\n",
    "#Both `KeyError` and `IndexError` are subclasses of `LookupError`, which means that they inherit from it and can be caught using a single \n",
    "#`except` block that handles `LookupError`. This allows for a more generic error handling approach when dealing with lookup-related exceptions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4e8d1f5c-69bd-4387-a36a-d45e63f9f630",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Module not found or unable to be imported.\n",
      "Module not found.\n"
     ]
    }
   ],
   "source": [
    "#5\n",
    "#`ImportError` is an exception class in Python that is raised when an import statement fails to find or load a module. \n",
    "#It indicates that there was an issue in importing a module, either because the module does not exist or because there was an error in the \n",
    "#import process.\n",
    "\n",
    "#Here's an example:\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError:\n",
    "    print(\"Module not found or unable to be imported.\")\n",
    "\n",
    "#In this example, we attempt to import a module named \"non_existent_module\". Since there is no such module, an `ImportError` is raised. \n",
    "#We catch the exception using a `try-except` block and print a custom error message.\n",
    "#Here's an example that demonstrates the use of `ModuleNotFoundError`:\n",
    "\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ModuleNotFoundError:\n",
    "    print(\"Module not found.\")\n",
    "\n",
    "#In this example, we catch the `ModuleNotFoundError` specifically, indicating that the issue was related to the module not being found. \n",
    "#This allows for more targeted exception handling in cases where module availability is critical."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "690889c1-9507-4c1c-a39a-7f7eb57ce56b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#When it comes to exception handling in Python, following best practices can help improve the reliability and maintainability of your code. \n",
    "#Here are some recommended practices:\n",
    "\n",
    "#1. Be specific in catching exceptions: Catch only the exceptions you expect and handle them appropriately. Avoid using bare `except` statements,\n",
    "#which can catch unexpected errors and make it harder to identify and debug issues.\n",
    "\n",
    "#2. Use multiple except blocks: When handling different exceptions, use separate `except` blocks for each specific exception. \n",
    "#This allows you to provide tailored error handling for different types of exceptions.\n",
    "\n",
    "#3. Handle exceptions at the appropriate level: Handle exceptions at a level of the code where you can effectively recover or \n",
    "#provide meaningful feedback to the user. Don't catch exceptions too broadly or too early,\n",
    "#as it may hide important error conditions or make debugging difficult.\n",
    "\n",
    "#4. Use `finally` for cleanup code: If you have code that needs to be executed regardless of whether an exception occurs or not, \n",
    "#use a `finally` block. This ensures that the cleanup code is always executed, even if an exception is raised and caught.\n",
    "\n",
    "#5. Avoid overly broad exception handling: Avoid catching and suppressing exceptions without proper handling or logging. \n",
    "#It can mask errors and make troubleshooting more challenging. Only catch exceptions that you can handle appropriately.\n",
    "\n",
    "#6. Use exception chaining: When catching an exception, you can re-raise it using `raise` without an argument to preserve the original traceback. \n",
    "#This provides better visibility into the root cause of the exception and helps with debugging.\n",
    "\n",
    "#7. Handle exceptions gracefully: Provide clear and informative error messages when exceptions occur. \n",
    "#It helps users understand what went wrong and provides guidance on how to resolve the issue.\n",
    "\n",
    "#8. Log exceptions: Logging exceptions and related information can be invaluable for debugging and monitoring. \n",
    "#Utilize Python's logging framework to capture exceptions, stack traces, and additional context for effective troubleshooting.\n",
    "\n",
    "#9. Use custom exception classes: Define your own exception classes when necessary to represent specific error conditions in your code. \n",
    "#Custom exceptions can provide more meaningful and structured error handling.\n",
    "\n",
    "#10. Test exception handling scenarios: Write unit tests that cover different exception handling scenarios in your code. \n",
    "#This ensures that your exception handling logic behaves as expected and helps catch any issues early on.\n",
    "\n",
    "#By following these best practices, you can write more robust and maintainable code that handles exceptions effectively, provides meaningful \n",
    "#error messages, and simplifies debugging and troubleshooting."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "25d6c09e-0d3a-4b5d-b7cd-57d9bf8f696c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
